import './screen/main-screen.js'
import './component/answer.js'
import './component/inputWrapper.js'
import './component/question.js'
import './screen/login-screen.js'
import './screen/register-screen.js'
import './screen/gameplay1-screen.js'
import './screen/gameplay2-screen.js'
import './screen/gameplay3-screen.js'
import './screen/mode-screen.js'
import './screen/end-screen.js'
import './screen/victory-screen.js'
import './screen/rank-screen.js'

import './component/td.js'
import './navigo.js'

